spring.application.name=login

spring.datasource.url=jdbc:postgresql://localhost:5432/Zephyra
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=YkN5Q3F6a1RtU2Z6dGh0V2x3b0lHb0VnVm1WbFN0ZlY=